/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAuth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["linkAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        get: operations["listMessages"];
        put?: never;
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerPushToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAIThreads"];
        put?: never;
        post: operations["createAIThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendAIMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/ai/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["summarizeConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversationId}/ai/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["draftConversationReply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Upgrade to the client WebSocket protocol defined by
         *     protocol/client-envelope.schema.json. Native clients authenticate with
         *     the normal Authorization header.
         */
        get: operations["connectRealtime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Error: {
            code: string;
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["Error"];
        };
        AuthStartRequest: {
            /** Format: email */
            email: string;
        };
        AuthStartResponse: {
            login_id: string;
            /** Format: date-time */
            expires_at: string;
            /** @description Development-only login code; never returned in production. */
            debug_code?: string;
        };
        AuthVerifyRequest: {
            login_id: string;
            code: string;
        };
        AuthRefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        /** @enum {string} */
        Platform: "signal" | "telegram";
        /** @enum {string} */
        AccountStatus: "unlinked" | "linking" | "live" | "offline" | "upgrade_required";
        Account: {
            id: string;
            platform: components["schemas"]["Platform"];
            external_id?: string;
            display_name: string;
            status: components["schemas"]["AccountStatus"];
            /** @enum {string} */
            hosting_mode: "desktop" | "self_hosted" | "hosted";
            /** Format: int64 */
            generation: number;
            /** Format: date-time */
            last_seen_at?: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateAccountRequest: {
            platform: components["schemas"]["Platform"];
            display_name?: string;
            /**
             * @default self_hosted
             * @enum {string}
             */
            hosting_mode: "desktop" | "self_hosted" | "hosted";
        };
        CreateAccountResponse: {
            account: components["schemas"]["Account"];
            enrollment: {
                /** @description Single-use worker enrollment token; returned once. */
                token: string;
                /** Format: date-time */
                expires_at: string;
            };
        };
        LinkAccountRequest: {
            /** @enum {string} */
            action: "start" | "finish" | "submit_code" | "submit_password";
            device_name?: string;
            /** @description E.164 number used to start Telegram authorization. */
            phone_number?: string;
            code?: string;
            /** Format: password */
            password?: string;
        };
        LinkAccountResponse: {
            /** @enum {string} */
            state: "qr_required" | "code_required" | "password_required" | "linked";
            qr_uri?: string;
            detail?: string;
        };
        Conversation: {
            id: string;
            account_id: string;
            provider_id: string;
            title: string;
            /** @enum {string} */
            kind: "direct" | "group";
            unread_count: number;
            /** Format: date-time */
            last_message_at?: string;
        };
        Message: {
            id: string;
            conversation_id: string;
            provider_id?: string;
            author_name: string;
            body: string;
            /** Format: date-time */
            sent_at: string;
            /** @enum {string} */
            direction: "incoming" | "outgoing";
            /** @enum {string} */
            status?: "pending" | "sent" | "failed" | "unknown";
        };
        SendMessageRequest: {
            body: string;
            idempotency_key: string;
        };
        SendMessageResponse: {
            command_id: string;
            message: components["schemas"]["Message"];
        };
        PushTokenRequest: {
            /** @enum {string} */
            platform: "apns" | "fcm" | "expo";
            token: string;
        };
        AIThread: {
            id: string;
            title: string;
            /** Format: date-time */
            created_at: string;
        };
        AIMessageRequest: {
            content: string;
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication failed. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        AccountId: string;
        ConversationId: string;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    startAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthStartRequest"];
            };
        };
        responses: {
            /** @description Login code accepted for delivery. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStartResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    verifyAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthVerifyRequest"];
            };
        };
        responses: {
            /** @description Login verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRefreshRequest"];
            };
        };
        responses: {
            /** @description Rotated token pair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts owned by the current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accounts: components["schemas"]["Account"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Account and one-time worker enrollment token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAccountResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account, cached content, and worker access scheduled for deletion. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    linkAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: components["parameters"]["AccountId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkAccountRequest"];
            };
        };
        responses: {
            /** @description Current link state and next user action. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkAccountResponse"];
                };
            };
            /** @description Worker is offline or link state is invalid. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listConversations: {
        parameters: {
            query: {
                account_id: string;
                cursor?: components["parameters"]["Cursor"];
                /** @description Ask a live worker to refresh the conversation cache. */
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cached conversations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conversations: components["schemas"]["Conversation"][];
                        next_cursor?: string;
                    };
                };
            };
        };
    };
    listMessages: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                /** @description Refresh Telegram history before returning the cache. */
                refresh?: boolean;
            };
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cached messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        messages: components["schemas"]["Message"][];
                        next_cursor?: string;
                    };
                };
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Send command accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description Worker is offline. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerPushToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushTokenRequest"];
            };
        };
        responses: {
            /** @description Push token registered. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAIThreads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI threads. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        threads: components["schemas"]["AIThread"][];
                    };
                };
            };
        };
    };
    createAIThread: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    title?: string;
                };
            };
        };
        responses: {
            /** @description AI thread. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIThread"];
                };
            };
        };
    };
    sendAIMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIMessageRequest"];
            };
        };
        responses: {
            /** @description Server-sent token and completion events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    summarizeConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent token and completion events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    draftConversationReply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    instruction?: string;
                };
            };
        };
        responses: {
            /** @description Server-sent token and completion events. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    searchMessages: {
        parameters: {
            query: {
                q: string;
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results from the bounded cache. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        messages: components["schemas"]["Message"][];
                        next_cursor?: string;
                    };
                };
            };
        };
    };
    connectRealtime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket upgrade accepted. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
