// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package contract

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AccountHostingMode.
const (
	AccountHostingModeDesktop    AccountHostingMode = "desktop"
	AccountHostingModeHosted     AccountHostingMode = "hosted"
	AccountHostingModeSelfHosted AccountHostingMode = "self_hosted"
)

// Defines values for AccountStatus.
const (
	Linking         AccountStatus = "linking"
	Live            AccountStatus = "live"
	Offline         AccountStatus = "offline"
	Unlinked        AccountStatus = "unlinked"
	UpgradeRequired AccountStatus = "upgrade_required"
)

// Defines values for ConversationKind.
const (
	Direct ConversationKind = "direct"
	Group  ConversationKind = "group"
)

// Defines values for CreateAccountRequestHostingMode.
const (
	CreateAccountRequestHostingModeDesktop    CreateAccountRequestHostingMode = "desktop"
	CreateAccountRequestHostingModeHosted     CreateAccountRequestHostingMode = "hosted"
	CreateAccountRequestHostingModeSelfHosted CreateAccountRequestHostingMode = "self_hosted"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Defines values for LinkAccountRequestAction.
const (
	Finish         LinkAccountRequestAction = "finish"
	Start          LinkAccountRequestAction = "start"
	SubmitCode     LinkAccountRequestAction = "submit_code"
	SubmitPassword LinkAccountRequestAction = "submit_password"
)

// Defines values for LinkAccountResponseState.
const (
	CodeRequired     LinkAccountResponseState = "code_required"
	Linked           LinkAccountResponseState = "linked"
	PasswordRequired LinkAccountResponseState = "password_required"
	QrRequired       LinkAccountResponseState = "qr_required"
)

// Defines values for MessageDirection.
const (
	Incoming MessageDirection = "incoming"
	Outgoing MessageDirection = "outgoing"
)

// Defines values for MessageStatus.
const (
	Failed  MessageStatus = "failed"
	Pending MessageStatus = "pending"
	Sent    MessageStatus = "sent"
	Unknown MessageStatus = "unknown"
)

// Defines values for Platform.
const (
	Signal   Platform = "signal"
	Telegram Platform = "telegram"
)

// Defines values for PushTokenRequestPlatform.
const (
	Apns PushTokenRequestPlatform = "apns"
	Expo PushTokenRequestPlatform = "expo"
	Fcm  PushTokenRequestPlatform = "fcm"
)

// AIMessageRequest defines model for AIMessageRequest.
type AIMessageRequest struct {
	Content string `json:"content"`
}

// AIThread defines model for AIThread.
type AIThread struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Title     string    `json:"title"`
}

// Account defines model for Account.
type Account struct {
	CreatedAt   time.Time          `json:"created_at"`
	DisplayName string             `json:"display_name"`
	ExternalId  *string            `json:"external_id,omitempty"`
	Generation  int64              `json:"generation"`
	HostingMode AccountHostingMode `json:"hosting_mode"`
	Id          string             `json:"id"`
	LastSeenAt  *time.Time         `json:"last_seen_at,omitempty"`
	Platform    Platform           `json:"platform"`
	Status      AccountStatus      `json:"status"`
}

// AccountHostingMode defines model for Account.HostingMode.
type AccountHostingMode string

// AccountStatus defines model for AccountStatus.
type AccountStatus string

// AuthRefreshRequest defines model for AuthRefreshRequest.
type AuthRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// AuthStartRequest defines model for AuthStartRequest.
type AuthStartRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AuthStartResponse defines model for AuthStartResponse.
type AuthStartResponse struct {
	// DebugCode Development-only login code; never returned in production.
	DebugCode *string   `json:"debug_code,omitempty"`
	ExpiresAt time.Time `json:"expires_at"`
	LoginId   string    `json:"login_id"`
}

// AuthVerifyRequest defines model for AuthVerifyRequest.
type AuthVerifyRequest struct {
	Code    string `json:"code"`
	LoginId string `json:"login_id"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	AccountId     string           `json:"account_id"`
	Id            string           `json:"id"`
	Kind          ConversationKind `json:"kind"`
	LastMessageAt *time.Time       `json:"last_message_at,omitempty"`
	ProviderId    string           `json:"provider_id"`
	Title         string           `json:"title"`
	UnreadCount   int              `json:"unread_count"`
}

// ConversationKind defines model for Conversation.Kind.
type ConversationKind string

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	DisplayName *string                          `json:"display_name,omitempty"`
	HostingMode *CreateAccountRequestHostingMode `json:"hosting_mode,omitempty"`
	Platform    Platform                         `json:"platform"`
}

// CreateAccountRequestHostingMode defines model for CreateAccountRequest.HostingMode.
type CreateAccountRequestHostingMode string

// CreateAccountResponse defines model for CreateAccountResponse.
type CreateAccountResponse struct {
	Account    Account `json:"account"`
	Enrollment struct {
		ExpiresAt time.Time `json:"expires_at"`

		// Token Single-use worker enrollment token; returned once.
		Token string `json:"token"`
	} `json:"enrollment"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LinkAccountRequest defines model for LinkAccountRequest.
type LinkAccountRequest struct {
	Action     LinkAccountRequestAction `json:"action"`
	Code       *string                  `json:"code,omitempty"`
	DeviceName *string                  `json:"device_name,omitempty"`
	Password   *string                  `json:"password,omitempty"`

	// PhoneNumber E.164 number used to start Telegram authorization.
	PhoneNumber *string `json:"phone_number,omitempty"`
}

// LinkAccountRequestAction defines model for LinkAccountRequest.Action.
type LinkAccountRequestAction string

// LinkAccountResponse defines model for LinkAccountResponse.
type LinkAccountResponse struct {
	Detail *string                  `json:"detail,omitempty"`
	QrUri  *string                  `json:"qr_uri,omitempty"`
	State  LinkAccountResponseState `json:"state"`
}

// LinkAccountResponseState defines model for LinkAccountResponse.State.
type LinkAccountResponseState string

// Message defines model for Message.
type Message struct {
	AuthorName     string           `json:"author_name"`
	Body           string           `json:"body"`
	ConversationId string           `json:"conversation_id"`
	Direction      MessageDirection `json:"direction"`
	Id             string           `json:"id"`
	ProviderId     *string          `json:"provider_id,omitempty"`
	SentAt         time.Time        `json:"sent_at"`
	Status         *MessageStatus   `json:"status,omitempty"`
}

// MessageDirection defines model for Message.Direction.
type MessageDirection string

// MessageStatus defines model for Message.Status.
type MessageStatus string

// Platform defines model for Platform.
type Platform string

// PushTokenRequest defines model for PushTokenRequest.
type PushTokenRequest struct {
	Platform PushTokenRequestPlatform `json:"platform"`
	Token    string                   `json:"token"`
}

// PushTokenRequestPlatform defines model for PushTokenRequest.Platform.
type PushTokenRequestPlatform string

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	Body           string `json:"body"`
	IdempotencyKey string `json:"idempotency_key"`
}

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	CommandId string  `json:"command_id"`
	Message   Message `json:"message"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken  string    `json:"access_token"`
	ExpiresAt    time.Time `json:"expires_at"`
	RefreshToken string    `json:"refresh_token"`
}

// AccountId defines model for AccountId.
type AccountId = string

// ConversationId defines model for ConversationId.
type ConversationId = string

// Cursor defines model for Cursor.
type Cursor = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CreateAIThreadJSONBody defines parameters for CreateAIThread.
type CreateAIThreadJSONBody struct {
	Title *string `json:"title,omitempty"`
}

// ListConversationsParams defines parameters for ListConversations.
type ListConversationsParams struct {
	AccountId string  `form:"account_id" json:"account_id"`
	Cursor    *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Refresh Ask a live worker to refresh the conversation cache.
	Refresh *bool `form:"refresh,omitempty" json:"refresh,omitempty"`
}

// DraftConversationReplyJSONBody defines parameters for DraftConversationReply.
type DraftConversationReplyJSONBody struct {
	Instruction *string `json:"instruction,omitempty"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Refresh Refresh Telegram history before returning the cache.
	Refresh *bool `form:"refresh,omitempty" json:"refresh,omitempty"`
}

// SearchMessagesParams defines parameters for SearchMessages.
type SearchMessagesParams struct {
	Q      string  `form:"q" json:"q"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// LinkAccountJSONRequestBody defines body for LinkAccount for application/json ContentType.
type LinkAccountJSONRequestBody = LinkAccountRequest

// CreateAIThreadJSONRequestBody defines body for CreateAIThread for application/json ContentType.
type CreateAIThreadJSONRequestBody CreateAIThreadJSONBody

// SendAIMessageJSONRequestBody defines body for SendAIMessage for application/json ContentType.
type SendAIMessageJSONRequestBody = AIMessageRequest

// RefreshAuthJSONRequestBody defines body for RefreshAuth for application/json ContentType.
type RefreshAuthJSONRequestBody = AuthRefreshRequest

// StartAuthJSONRequestBody defines body for StartAuth for application/json ContentType.
type StartAuthJSONRequestBody = AuthStartRequest

// VerifyAuthJSONRequestBody defines body for VerifyAuth for application/json ContentType.
type VerifyAuthJSONRequestBody = AuthVerifyRequest

// DraftConversationReplyJSONRequestBody defines body for DraftConversationReply for application/json ContentType.
type DraftConversationReplyJSONRequestBody DraftConversationReplyJSONBody

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// RegisterPushTokenJSONRequestBody defines body for RegisterPushToken for application/json ContentType.
type RegisterPushTokenJSONRequestBody = PushTokenRequest
